# server port config
server:
  port: 8080

# db connection info
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.today:1521:xe
    username: C##AUTOCSS
    password: AUTOCSS
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\dev\empImg

  # jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        '[format_sql]': true

## HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ??????.
## Secret ?? ?? ???? Base64? ???? ?? ??
## https://8gwifi.org/jwsgen.jsp ???? Generate JWS keys? ???? ??? ??? ??? SharedSecret(Generated ..)??? ?? ??? ??? ?????
jwt:
  secret: ejiSfPXxOMUuMXEU932MCy0adrbtkSlKeWcVZ0app6DpenURBmjaClhGTB4hR2dzzBhbMshXio46kUOtLs3tdw==

# Logging Level
logging:
  level:
    root: info

## 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  ## WebConfig에 세팅
  add-resource-locations: classpath:/static/applyMimgs/
  add-resource-handler: /applyMimgs/**

  image-dir: src/main/resources/static/applyMimgs
  image-url: http://localhost:8080/applyMimgs/

  image-dir2: C:\dev\empImg
  image-url2: http://localhost:8080/empImg/

## Swagger 설정
springdoc:
  packages-to-scan: com.css.autocsfinal
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true

